#! /bin/bash

# Usage:
# $ ./llnl username

set -e

if [ "$1" = "" ]; then
    echo "Usage:"
    echo "$ ./llnl username"
    exit 1
fi

sudo ./openconnect --script ./vpnc-script --authgroup=llnl-vpnb -u $1 vpn.llnl.gov
